apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xwzm2u9h4-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:050b0241d1a8bab23bd7d17b00b2a2ac403411cd@sha256:3a308fbd6fc2a2b11da6e49ed09f27514f79879bbb4c1f8003f029a24b9dd159
          name: container-image
